// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    dbUrl: 'mongodb://127.0.0.1:27017/doubanDB',
    cookie_secret: 'cookie_secret',
    douban_user_name: 'straybird',
    douban_user_id: 'staybird',
    serverPort: 3000,
    doubanAPIKey: '02b703f49616c50a08250bddc2444f1e'
  };

}).call(this);
