// Generated by CoffeeScript 1.6.3
(function() {
  var Mongoda, doubanUser, settings, _import;

  _import = require('../import/import');

  Mongoda = require('../models/mongoda');

  settings = require('../settings');

  doubanUser = require('../models/doubanUser');

  exports.index = {
    get: function(req, res) {
      return res.render('index');
    }
  };

  exports.upload = {
    post: function(req, res) {
      var col, data;
      col = req.body['col'];
      data = req.body['data'];
      data = JSON.parse(data);
      _import.insertData(col, data);
      return res.send('1');
    }
  };

  exports.findone = {
    get: function(req, res) {
      return (new Mongoda(settings.dbUrl)).open(function(err, db) {
        var col;
        col = db.collection(req.param('col'));
        return col.findOne({}, function(err, item) {
          return res.send(item);
        });
      });
    }
  };

  exports.user = {
    get: function(req, res, douban_user_id) {
      return res.render('index', {
        doubanKey: settings.doubanAPIKey,
        domain: settings.domain,
        douban_user_id: douban_user_id,
        douban_user_name: douban_user_id
      });
    },
    post: function(req, res, douban_user_id) {
      return doubanUser.data(douban_user_id, function(userData) {
        return res.send(userData);
      });
    }
  };

  exports.update = {
    post: function(req, res, douban_user_id) {
      var status;
      status = doubanUser.update(douban_user_id);
      return res.send(status);
    }
  };

}).call(this);
