// Generated by CoffeeScript 1.6.3
(function() {
  var MongoClient, Mongoda, settings;

  MongoClient = (require('mongodb')).MongoClient;

  settings = require('../settings');

  Mongoda = function(dbUrl) {
    var _db, _dbUrl, _t;
    _t = this;
    _db = null;
    _dbUrl = dbUrl;
    this.open = function(onOpen) {
      MongoClient.connect(_dbUrl, function(err, db) {
        if (err) {
          console.error('DBError', err);
        }
        _db = db;
        if (onOpen) {
          onOpen(err, _t);
        }
        return _t;
      });
      return this;
    };
    this.close = function() {
      if (_db) {
        _db.close;
      }
      return this;
    };
    this.collection = function(collectionName, onData) {
      if (onData) {
        return _db.collection(collectionName, (function(err, col) {
          return onData(col);
        }));
      } else {
        return _db.collection(collectionName);
      }
    };
    return this;
  };

  module.exports = Mongoda;

}).call(this);
